### ISSUE TITLE
jamtaba2 plugin in Cakewalk

### ISSUE THREAD

**Issue by ayamel64** [elieserdejesus/JamTaba#1285]
hello ,

Hi, I'm new. I have been using jamtaba2 for a few weeks and I really like it. The only problem is that now using the plugin in Cakewalk I can't get into the rooms. Listening is instead possible. (64bit version) thanks. Daniele

**Comment by fmarinheiro** [comment]
> hello ,
> 
> Hi, I'm new. I have been using jamtaba2 for a few weeks and I really like it. The only problem is that now using the plugin in Cakewalk I can't get into the rooms. Listening is instead possible. (64bit version) thanks. Daniele

Checkout #1279 it's probably a duplicate.

**Comment by elieserdejesus** [comment]
Released a new version right now, this problem is fixed.

**Comment by ayamel64** [comment]
Hi , 
I downloaded the new version today but the problem remains.
Thanks daniele

**Comment by jonjamcam** [comment]
> I downloaded the new version today but the problem remains.

@ayamel64 what exactly is the problem? Can you give more information?

Another user reported sonar has a keyboard issue in https://github.com/elieserdejesus/JamTaba/issues/1262 .

**Comment by ayamel64** [comment]
the problem is that using jamtaba as a cakewalk plugin does not allow me to enter the rooms but only to listen from outside. thanks

Inviato da iPhone

**Comment by ayamel64** [comment]
Ok 👍 
Download in This moment .it’s ok
Thank 💋

Inviato da iPhone
